"use strict";

export default [
	"A inteligência artificial não é páreo para a estupidez natural!",
	"A tendência é piorar.",
	"A vida é curta e mesmo assim você vai continuar trabalhando em projetos bosta.",
	"A única coisa que você faz certo é errar",
	"Agradeça seu pai por ele te amar mesmo você sendo um merda.",
	"Algumas pessoas nasceram bonitas,outras nasceram inteligentes... Você apenas nasceu!",
	"Aquela festa parece legal... Ninguém te convidou.",
	"As pessoas só te incentivam para rir do seu fracasso.",
	"As pessoas só te respondem para você parar de encher o saco.",
	"As vezes a vida te levanta  só pra você cair de novo.",
	"Até papel higiênico tem um rolo e você não",
	"Azar no amor, azar no dinheiro e sorte no azar.",
	"Calma, o pior ainda está por vir.",
	"Comer que nem um filho da puta não vai esconder o fracasso da sua vida.",
	"De longe você é feio e de perto parece que está longe",
	"Dia dos Namorados, Dia do Amigo. Um dia inventam uma data de algo que você tenha",
	"Ela ainda se lembra de você. Com nojo.",
	"Ela gosta do seu melhor amigo.",
	"Ela não é dificil, você que é feio.",
	"Ela pediu um tempo porque queria dar para outro.",
	"Ela saiu com você para comer de graça.",
	"Ela só te usou para fazer ciúme no ex.",
	"Ele ainda se lembra de você. Com raiva!",
	"Ele só te comeu por falta de opção.",
	"Está dando tudo certo. Aí você acorda...",
	"Finalmente ela olhou pra você. E te achou feio.",
	"Hoje você tem uma nova chance de fazer a mesma merda de sempre",
	"Logo logo ano novo e mais vida bosta",
	"Mais um dia de derrotas te aguarda",
	"Mais um dia lindo para você fracassar",
	"Mais um dia que passa e tua insignificância prevalece.",
	"Mais um sábado com S de sofrimento, saudade e solidão",
	"Ninguém acha graça no que você diz.",
	"Ninguém liga para o que você acha",
	"Ninguém liga para o que você pensa",
	"Nunca diga que sua vida não pode ficar pior",
	"Não desanime com a derrota de hoje. Amanhã tem outra.",
	"O tempo passa e você continua sendo otário",
	"Para de bater punheta pra desenho.",
	"Para de tentar criar polêmica pra chamar atenção. Todo mundo te acha um bosta.",
	"Pra ser inútil você tem que melhorar muito.",
	"Qualquer companhia é melhor que a sua.",
	"Se você não conseguir de primeira, remova todas as evidências de que você ao menos tentou!",
	"Seja feliz. A base de remédios!!!",
	"Seu cupido deve ter morrido",
	"Seu dia vai ser uma bosta.",
	"Seu pai só teria um dia feliz se não tivesse você como filho.",
	"Seu signo não justifica sua chatice",
	"Seus desejos nunca se tornarão realidade",
	"Seus sonhos nunca se realizarão.",
	"Sua cara metade virou gay!",
	"Sua existência não significa nada",
	"Sua mãe deveria ter engolido.",
	"Sua sombra só te segue porque é obrigada.",
	"Sua vida é uma merda",
	"Só pelo fato de uma garota bonita gostar das mesmas coisas que você, isso não faz dela a sua alma gêmea.",
	"Ta todo mundo transando menos você.",
	"Talvez as coisas mudem. Para pior",
	"Tem peito grande mas é gorda.",
	"Toda família tem aquele membro fracassado... A sua tem você.",
	"Toma aqui o seu boleto pra você ir pagar de trouxa",
	"Tudo saiu como o esperado. Errado.",
	"Uma mulher te abraçou. Era sua mãe",
	"Uma mulher te cantou...era um travesti.",
	"Uns têm dinheiro, outros tem beleza e você... tem que estudar",
	"Vai dar merda.",
	"Você já deveria estar magro de tanto que corre atrás da felicidade.",
	"Você nasceu para ser feito de otário.",
	"Você nunca vai conseguir.",
	"Você precisa só de uma mãozinha...Bem no meio da fuça!",
	"Você só faz peso na terra.",
	"Você vai morrer infeliz e sozinho.",
	"Você é aquele da família que não deu certo",
	"Você é um desperdício de esperma.",
	"Você é um erro."
]
